version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: 'mongo'
    restart: always
    ports:
      - 27017:27017
  northwindproject:
    build: ./
    image: 'spring:v1'
    container_name: 'northwindproject'
    restart: always
    ports:
      - 8080:8080
